# The MEAP Pipeline v1.1.2

This pipeline was developed at the Moura research group at the University of Gdańsk and previously the
Muzeum i Instytut Zoologii PAN in Poland.
The purpose for this pipeline is to create a user friendly and reproducible pipeline that can 
employ publically available algorithms and tools, to analyze de novo exome NGS data. The script was 
designed as part of the SONATA 2018/31/D/NZ8/02835 project funded by the Polish NCN, focused on
analysing temporal patterns of immune system genes in Mediterranean striped dolphin (Stenella coeruleoalba)

This pipeline serves as a shell around pre-existing tools and should be used as such. It has been tested on the 
system used for the project, but we cannot guaranteed compatibility with all systems. Certain settings 
are predefined by the project for which this tool was created, however due to the accessibility of bash scripting
users can easily change settings for each tool and step. If you do use this script, please consider citing the 
following publication: Moura et al XXXXX

*** 

## Workflow

MEAP was developed to process paired end illumina based sequencing data and run exome analysis using it.
The tools used by the pipeline are assumed to be preinstalled and include in the user's PATH
*[option -1] Trim Galore! v0.6.5				(https://www.bioinformatics.babraham.ac.uk/projects/trim_galore/)
	* Cutadapt v2.10				(https://pypi.python.org/pypi/cutadapt/)
	* FastQC v0.11.9				(https://www.bioinformatics.babraham.ac.uk/projects/fastqc/)
*[option -2] Bowtie2 v2.4.1				(http://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.4.1/)
*[option -2] SAMtools v1.11				(https://www.htslib.org/download/)
*[option -3] R v4.0.3				(http://www.r-project.org/)
*[option -3] bedtools v2.29				(https://bedtools.readthedocs.io/en/latest/)
	
Please make sure these tools are installed and that their executables are added to your PATH 
However, if the user doesn't have these tools installed, an attempt has been made to create an automated
installation for each tool. Installation can be activated with [option -i or --installsoftware]. The user can supplement
this option with string which will be interpreted as a directory where instalation should take place, or if left blank, 
the default instalation folder ~/Software will be used. No sudo required.
Unfortunately CutAdapt, Python, Java and R have to be installed manually as they require either Sudo or Pip. 

The pipeline assumes all previous steps have been performed and are in the output folder structure generated by this pipeline
	Output_folder/
		|-	Trimmed_reads/
			|-	sample1/
				|- sample1_*_R1_001_val_1.fq
				|- sample1_*_R2_001_val_2.fq
			|-	.../
		|-	Mapping_to_ref/
			|-	sample1/
				|- sample1.sorted.bam
			|-	.../
		|-	Coverage_analysis/
				|- Coverage_distributions.pdf
				|- Sample_read_quality.pdf
				|- Analyzed_Coverage_Data.tsv

Data can be generated into a user defined folder using [-o|--outputfolder path/to/folder] otherwise the default is set to ~/output.
This pipeline assumes the user has rights to install in his/her working directory, if this is not the case, the pipeline will not function properly

The following processes have been incorporated into this pipeline


#### 1. NGS Read data processing [option -1]
The pipeline does not demultiplex data, and if samples have been multiplexed, it is up to the user to do this prior to 
running MEAP. 
This step assumes all sequencing files have the standard illumina data naming system and are paired end datasets. 
The user can specify whether or not the data contains a prefix.
[prefix]_[sample_name]_*R1*fa*q.gz / [prefix]_[sample_name]_*R2*fa*q.gz 
Please note that testing showed that the file extension faq.gz is not recognised. 
If this is your case, then rename to the extension fastq.gz.

The pipeline will extract Sample name from the file_name based on the first string before the next underscore, and will assume the file name has a complemantary R2 variant for the reverse read file.
The pipeline also assumes the read data to be in FastQ format, if this is not the case, it cannot be trimmed and analyzed and user should skip to step 2.

The read processing is done by Cutadapt, FastQC and TrimGalore. 
CutAdapt removes standard adapters from the data that are commonly used for illumina sequencing.
Trimgalore then trim low quality basecalls from the reads, user can change this cutoff using [option --phred int], the default value is set to 30 (stringent)
FastQC generates some general statistics on the newly trimmed reads for downstream analysis which can be found in each sample folder under Trimmed_reads/ 


#### 2. Mapping reads
This step requires the user to have a reference genome [option -g|--genomereference path/to/file] which can be used for variance calling. 
If this is a de novo project on a non-model organism, please look into assembling a reference first.
The pipeline expects the reference to be in fasta format. 

Bowtie is used to map reads to the reference
Samtools is used to store the data as a sorted bam file


#### 3. Assessing mapping quality
This step extract the number of read pairs from trimmed reads and employs bedtools to generate mapping statistics.
A custom R script processes this information and generates an interpretive plot for downstream analysis. 
Please note that the statistics produce at this step give a rough idea of the output of the mapping step, and
are intende as a first assessment of mapping success. They can help identify some pontetial issues with 
the mapping before proceeding with the rest of the pipeline. 