#!/bin/bash
###################################################################################################################
# Script designed for the Stenella immunogenome project 2018/31/D/NZ8/02835, funded by the Polish NCN.
# This script is intended as a rough pipeline to automate exome mapping analysis using tools such as 
# Trimgalore, Bowtie and samtools. The script expects the user to have added the tools to their PATH, 
# otherwise the user can use option -i for local instalation of the software packages (this will take longer)
# The script is annotated to facilitate its use by other research groups, but is provided as is. 
# It has been tested in our system where it works corectly, but we cannot guarantee compatibility with all systems.
# Newer versions of the tools implemented might require some code changes, but users are free to modify the script 
# to meet their needs. If you do use this script, please consider citing the following publication:
# Moura et al XXXXX
###################################################################################################################

# Current directory, and the directory where the script is present
CURRENT_DIR="$(pwd)"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)/"

# A few switches and basic default settings
CORES=1
MEMORY=6000
PHRED=30
R_PATH=false 
G_PATH=false
C_PATH=false
D_PATH=false
TRIMMER_SWITCH=false
MAPPER_SWITCH=false
BAM_MAP_FILTER=2
COV_ANALYSIS=false
COORDINATES_SWITCH=false
OUTPUT_SWITCH=false
INSTALL_DIR=~/Software
INSTALLER_SWITCH=false
POST_PROCESS_SWITCH=false
GATK_SWITCH=true
BCFTOOLS_MPILEUP_SWITCH=false
R_PREFIX="Illumina_"
BOOTSTRAP=1000
GAP_OPEN_VAL=2
GAP_EXTENT_VAL=0.5


##########################################################################################################
# The script provides several options/arguments for specific functionality 
##########################################################################################################
# Print this message when using the -h or --help tag 
show_help() {
cat << EOF

Usage: ${0##*/} [-1 -2 -3] [-t var ] ...
The MEAP pipeline is developed around pre-existing gold standard tools.
The user can process Illumina NGS data using the following options
	-0			Run ALL analysis [-1 -2 -3]
	-1			Trim reads with trim galore [on/off, default off] [requires option -r]
	-2			Map trimmed reads to reference genome using bowtie2 
				[requires option -g]
	-3			Automatically generate coverage data from output generated by 
				the read mapping in option -2. This step uses a custom R script and
				can also be done manually with "MEAP_coverage_analysis.R"
	-i|--installsoftware	Install software if it's not present on the PATH. User can specify
				a dedicated directory, [/path/to/folder, default ~/Software]
	-t|--threads		Number of threads for certain software packages [integer, default=1]
	-m|--memory		Amount of memory available in MB [integer, default=500]
	-o|--outputfolder	Specify a specific output directory, 
				otherwise the [/path/to/folder, default ./outputs]
	-r|--readfolder		Folder containing read files for processing, these should be 
				paired and contain R1*fa*q [path/to/folder], needed for -0, -1 & -3
	-p|--prefix		If option -r is used, user can specify prefix for read files [default Illumina_], i.e.
						[user_input][sample_name]_[project_code]_[L_number]_R2.fastq.gz  
	-g|--genomereference	Reference genome [/path/to/file], needed for -0 & -2
	Additional options for Trim_Galore to designate what the cutoff is for "bad" basecalls
	--phred			[integer], This option can be set with a value, for determine the quality 
				cutoff for read trimming. [Default 30]
	Additional options for the Bowtie2 mapping
	--map_filter		[integer] This option can be set to discard mapped reads below this threshold
				[Default 1]
	-h|--help		Show Help
EOF
}                

##########################################################################################################
# Command line argument parsing is done here mostly using binary switches
##########################################################################################################
while :; do
	case "$1" in
        -r|--readfolder)  
			# If there is an argument given by the user, this will show up as $2
			# We double check that this argument is an actual argument and not just another
			# option by checking if there is no dash at the start of the argument
			# '-option' is ignored while 'option' is considered a super provided argument
			if [ "$2" ] && [[ ! $2 == -* ]]; then
				if [ -d "$2" ]; then
				  ### Take action if $DIR exists
					echo "Raw read directory provided by user: ${2}";
					R_PATH=${2%/};
				else
				  ###  Control will jump here if $DIR does NOT exists ###
					echo "Raw read directory [-r] not supplied or does not exist";
					exit 1;
				fi
			# If an argument is passed, an additional shift is needed so the script doesn't then
			# read the argument again as an option
			shift
			fi
		    ;;
	-p|--prefix)  
		if [ "$2" ] && [[ ! $2 == -* ]]; then
			echo "Read prefix provided by user: ${2}";
			R_PREFIX=${2}
			shift
		else
			echo "No Read file prefix [-p] supplies, assuming the data has no prefix";
			R_PREFIX=""
		fi
		;;
	-g|--genomereference)
		if [ "$2" ] && [[ ! $2 == -* ]]; then
			if [ -f "$2" ]; then
				echo "Genome file provided by user: ${2}";
				G_PATH=$(readlink -e ${2})
			else
				echo "Genome reference not supplied or does not exist";
				exit 1;
			fi
		shift
		fi
		;;
	--map_filter)
		if [ "$2" ] && [[ ! $2 == -* ]]; then
			if [[ $2 =~ ^-?[0-9]+$ ]] ; then
				BAM_MAP_FILTER="$2"
				echo "Phred score cutoff: $PHRED ";
			else
				echo "Mapping filter provided by user is non numerical, default is used [2]";
			fi
			shift
		else
			echo "No value provided after option --map_filter, default is used [2]";
			continue
		fi
		;;
	
	# When the user specifies the numbered option, we just change the options from false
	# to true so the script knows which subsection to run and which to ignore
	-0)
		TRIMMER_SWITCH=true
		MAPPER_SWITCH=true
		COV_ANALYSIS=true
		;;
	-1)
		TRIMMER_SWITCH=true
		;;
	-2)
		MAPPER_SWITCH=true
		;;
	-3)
		COV_ANALYSIS=true
		;;
	-i|--installsoftware)
		INSTALLER_SWITCH=true
		if [ "$2" ] && [[ ! $2 == -* ]] ; then
			echo "Instalation directory provided by user: ${2}"
			INSTALL_DIR=${2%/}
			shift
		fi
		mkdir -p ${INSTALL_DIR}
		# If software is to be installed, we'll also check if this has not 
		# already been done previously in the same directory by adding all
		# the folder paths to the user PATH variable. This way when the
		# script checks for software on the PATH, it will find software
		# that was previously installed with this script
		if [ -n "$(ls -A ${INSTALL_DIR})" ]; then
			SOFTWARE_IN_INSTALL_DIR="${INSTALL_DIR}/*/"
			for f in $SOFTWARE_IN_INSTALL_DIR; do
				export PATH=$PATH:$f
			done
			SOFTWARE_IN_INSTALL_DIR="${INSTALL_DIR}/*/bin/"
			for f in $SOFTWARE_IN_INSTALL_DIR; do
				export PATH=$PATH:$f
			done
		fi
		;;
	--phred)  
		if [ "$2" ] && [[ ! $2 == -* ]]; then
			if [[ $2 =~ ^-?[0-9]+$ ]] ; then
				PHRED="$2"
				echo "Phred score cutoff: $PHRED ";
			else
				echo "Phred score provided by user is non numerical, default is used [30]";
			fi
			shift
		else
			echo "No value provided after option --prhed, default is used [30]";
			continue
		fi
		;;
	-c|--coordinates)  
		if [ "$2" ] && [[ ! $2 == -* ]]; then
			if [ -f "$2" ]; then
				echo "Coordinate file provided by user: ${2}"
				C_PATH=$(readlink -e ${2});
			else
				echo "Coordinate file not supplied or does not exist";
				echo "Please refer to https://github.com/Intel-HLS/GenomicsDB/wiki"
				echo "for the appropriate format."
				exit 1;
			fi
		shift
		fi
		;;
	-t|--threads)
		if [ "$2" ] && [[ ! $2 == -* ]]; then
			# As these are numerical, we'll double check whether the argument starts with and 
			# only contains numeric values
			if [[ $2 =~ ^-?[0-9]+$ ]] ; then
				CORES="$2"
				echo "Cores provided by user: $CORES ";
			else
				echo "Cores provided by user is non numerical, default is used [1]";
			fi
			shift
		else
			cho "No value provided after option -t|--threads, default is used [1]";
			continue
		fi
		;;
	-m|--memory)
		if [ "$2" ] && [[ ! $2 == -* ]]; then
			if [[ $2 =~ ^-?[0-9]+$ ]] ; then
				MEMORY="$2"
				echo "Memory set by user: $MEMORY ";
			else
				echo "Memory set by user is non numerical, default is used [500]";
			fi
			shift
		else
			echo "No value provided after option -m|--memory, default is used [500]";
			continue
		fi
		;;
	
	-h|--help) 
		show_help >&2
		;;
	-o|--outputfolder)
		if [ "$2" ] && [[ ! $2 == -* ]]; then
			OUTPUT_SWITCH=${2%/};
			mkdir -p $OUTPUT_SWITCH;
			echo "Output directory provided by user: ${2}";
			shift
		else
			echo "No output directory provided [-o], default is used [output/]";
		fi
		;;
	*)
		break
	esac
	shift
done

##########################################################################################################
# Here is some exemption handling in case the user didn't supply mandatory options
##########################################################################################################
# If no analysis is set, then exit
if [[ "$TRIMMER_SWITCH" = false ]] && [[ "$COV_ANALYSIS" = false ]] && [[ "$MAPPER_SWITCH" = false ]];  then
	exit 1;
fi

# If user provided a -o [value] argument, output directory will be set to [value]
# Otherwise the default is just "output". This directory will be attempted to be made (mkdir -p)
#echo ${OUTPUT_SWITCH}
if [ "$OUTPUT_SWITCH" = false ]; then
	mkdir -p output
	OUTPUT_SWITCH="output"
	echo "Output folder is set to ${OUTPUT_SWITCH}";
elif [ "$OUTPUT_SWITCH" = true ]; then
	mkdir -p output
	echo "Output folder is set to ${OUTPUT_SWITCH}";
fi
command -v python >/dev/null 2>&1 || { echo >&2 "Python is not installed";
	echo "Use option -i for automatic installation, or add you local installation to your PATH"
	exit 1;
}

# Check if the system has python installed in PATH... if not, check first if Python3 is installed instead
# If Python3 is installed, the user should put a symlink to python3 in /usr/bin/env called python 
# If Python3 is also not installed, let the user know they need to install it
command -v python >/dev/null 2>&1 || { 
	command -v python3 >/dev/null 2>&1 || {
		echo >&2 "Python3 is not installed";
		echo "This software should be installed through sudo, therefore exiting";
		echo "More information on installing python3 visit https://www.python.org/";
		echo "or for a local installation without sudo right,"
		echo "https://help.dreamhost.com/hc/en-us/articles/115000702772-Installing-a-custom-version-of-Python-3"
		exit 1;
	}
}


#######
# Here are some tools that are used more than once in the script. To handle presence of the tools in PATH and installing them multiple times, we'll make one 
# main function that we can call on multiple times to save linespace.
#######

# Several tools need Java version 11 or higher, therefore this function can be called on
# And it will check the java version and stop the script if it's not high enough
java_check () {
	echo "Checking Java installation"
	if type -p java; then
		_java=java
	elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
		_java="$JAVA_HOME/bin/java"
	else
		echo "Java is not installed, this pipeline needs Java 11 or higher to be installed prior to analysis";
		exit 1;
	fi
	if [[ "$_java" ]]; then
		version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
		if [[ "$version" > "11.0" ]]; then
			echo "Java version ${version} is installed, proceeding with analysis" 
		else
			echo "Java version ${version} is outdated, need version >11, please install and try again";
			exit 1;
		fi
	fi
}

# Several steps require Samtools/BCFtools therefore this function can be called on
# And it will install Samtools if not present
# Because the installation of Samtools and BCFtools is identical (the same group makes both tools, instead of writing two separate 
# functions, we'll make one generic one that relies on a user provided variable that states if its sam or bcf, this variable will be stored as $1
HTBtools_check () {
	# Samtools needs to be installed from source, therefore this one is a bit more comprehensive in that it uses the ./configure
	# and make files to do a complete clean install of samtools. 
	# The ${1} is the argument provided, which is either 'sam' or 'bcf', this way we can install both with one function (saves lines)
	command -v samtools >/dev/null 2>&1 || { echo >&2 "Samtools is not installed";
		if [ "$INSTALLER_SWITCH" = true ]; then
			echo "Installing now.";
			wget https://github.com/samtools/samtools/releases/download/1.11/samtools-1.11.tar.bz2 -P ${INSTALL_DIR} -q -o /dev/null
			wait $!;
			tar -xjf ${INSTALL_DIR}/samtools-1.11.tar.bz2 --directory ${INSTALL_DIR}/ 
			wait $!;
			cd samtools-1.11/
			./configure --prefix=${INSTALL_DIR}/samtools/ 
			wait $!
			make -s 
			wait $!
			make install 
			wait $!
			cd ../
			rm -r ${INSTALL_DIR}/samtools-1.11/
			rm ${INSTALL_DIR}/samtools-1.11.tar.bz2
			export PATH=$PATH:${INSTALL_DIR}/samtools/;
		else
			echo "Use option -i for automatic instalation, or add you local instalation to your PATH";
			exit 1;
		fi
	}
}

##########################################################################################################
# Now that the options are read, based on the selection 1,2,3 the pipeline will run several processes
##########################################################################################################

###############################################
# Option 1, Trimgalore
###############################################
# If switch is true, then we can run this section. Switch will only be true if the user gave the option
# to do so
if [ "$TRIMMER_SWITCH" = true ]; then
	echo "Starting raw read trimming [option -1]";
	if [ "$R_PATH" = false ]; then
		echo "Option -r not supplied, cannot find read folder, exit";
		exit 1;
	fi
	# Install TrimGalore if not already there
	# First it will check presence of 'trim_galore' on PATH, if this returns a null statement
	# it will continue with the next step
	command -v trim_galore >/dev/null 2>&1 || { echo >&2 "TrimGalore is not installed";
		# If the user added option -i for instalation, it will check the switch and continue
		if [ "$INSTALLER_SWITCH" = true ]; then
			# Most software is just downloaded and unpacked, with little to no output to stderr or stdout
			# Output supression is done to keep the command line clean, but can result in errors being hidden
			# therefore it should be double checked by the user if everything is functioning as firewalls
			# or lack of writing rights to a folder could disrupt this process
			echo "Installing now."
			wget https://github.com/FelixKrueger/TrimGalore/archive/0.6.5.tar.gz -P ${INSTALL_DIR} -q -o /dev/null
			wait $!
			tar -zxf ${INSTALL_DIR}/0.6.5.tar.gz --directory ${INSTALL_DIR}/ 
			wait $!
			rm ${INSTALL_DIR}/0.6.5.tar.gz
			export PATH=$PATH:${INSTALL_DIR}/TrimGalore-0.6.5/
		else
			echo "Use option -i for automatic instalation, or add you local instalation to your PATH"
			exit 1;
		fi
	}
	command -v fastqc >/dev/null 2>&1 || { echo >&2 "FastQC is not installed";
		if [ "$INSTALLER_SWITCH" = true ]; then
			echo "Installing now.";
			cd ${INSTALL_DIR}
			wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip -q -o /dev/null
			wait $!;
			jar -xf fastqc_v0.11.9.zip  
			wait $!;
			rm fastqc_v0.11.9.zip;
			export PATH=$PATH:${INSTALL_DIR}/FastQC/;
			cd ${CURRENT_DIR}
		else
			echo "Use option -i for automatic instalation, or add you local instalation to your PATH";
			exit 1;
		fi
	}
	command -v cutadapt >/dev/null 2>&1 || { echo >&2 "Cutadapt is not installed";
		echo "This software can only be installed through conda/sudo or pip/pip3, therefore exiting";
		echo "More information on https://cutadapt.readthedocs.io/en/stable/installation.html";
		exit 1;
	}
	FILES="${R_PATH}/*R1*fa*q*.gz"
	# Check if there are actually any files in the specified folder
	if [ -n "$(ls -A ${FILES})" ]; then
		FILES_COUNT=($FILES)
		FILES_COUNT=${#FILES_COUNT[@]}
		echo "A total of ${FILES_COUNT} unique sequenced samples were found in ${R_PATH}"
	else
		echo "There appear to be no read files ending with *R1*fa*q*.gz in the directory specified with -r";
		exit 1;
	fi
	
	for f in $FILES
	do
		#Extract all the information from the read titles, such as sample name, and which of the pair the file belongs to
		R1_FILE_NAME=${f##*/}
		echo ${R1_FILE_NAME}
		SAMPLE_NAME=${R1_FILE_NAME##*${R_PREFIX}}
		echo ${SAMPLE_NAME}
		SAMPLE_NAME=${SAMPLE_NAME%%_*}
		echo ${SAMPLE_NAME}
		R2_FILE_NAME=${R1_FILE_NAME%_R1*}_R2${R1_FILE_NAME##*_R1}
		echo ${R2_FILE_NAME}
		if [ -f ${R_PATH}/${R_PREFIX}${R1_FILE_NAME##*${R_PREFIX}} ]; then
			echo "Processing sample ${SAMPLE_NAME}"
		else
			echo "${f} appears to have a different prefix than ${R_PREFIX}. Please provide a correct prefix with -p";
			exit 1;
		fi
		mkdir -p ${OUTPUT_SWITCH}/Trimmed_reads/${SAMPLE_NAME}
		trim_galore -j ${CORES} --fastqc --illumina -q ${PHRED} --dont_gzip --max_n 1 --retain_unpaired --suppress_warn -o ${OUTPUT_SWITCH}/Trimmed_reads/${SAMPLE_NAME} --paired ${R_PATH}/${R1_FILE_NAME} ${R_PATH}/${R2_FILE_NAME}
		echo "Finished processing reads for sample ${SAMPLE_NAME}"
	done
	echo "Finished trimming reads"
fi

#################################################
# Option 2, read mapping to reference
##################################################

if [ "$MAPPER_SWITCH" = true ]; then
	echo "Starting read mapping [Option -2]"
	if [ "$G_PATH" = false ]; then
		echo "Option -g not supplied, cannot find genome reference, exit";
		exit 1;
	fi
	command -v bowtie2 >/dev/null 2>&1 || { echo >&2 "Bowtie2 is not installed";
		if [ "$INSTALLER_SWITCH" = true ]; then
			echo "Installing now.";
			cd ${INSTALL_DIR}
			wget https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.4.1/bowtie2-2.4.1-linux-x86_64.zip -q -o /dev/null
			wait $!;
			jar  -xf  bowtie2-2.4.1-linux-x86_64.zip 
			wait $!;
			rm bowtie2-2.4.1-linux-x86_64.zip ;
			export PATH=$PATH:${INSTALL_DIR}/bowtie2-2.4.1-linux-x86_64/;
			cd ${CURRENT_DIR}
		else
			echo "Use option -i for automatic instalation, or add you local instalation to your PATH";
			exit 1;
		fi
	}
	# Run the HTBtools_check with 'sam' argument to check for 'sam'tools and if not present, install it
	HTBtools_check sam
	bowtie2-build --threads ${CORES} ${G_PATH} ${G_PATH}_index
	FILES="${CURRENT_DIR}/${OUTPUT_SWITCH}/Trimmed_reads/*/*_val_1.fq"
	MAPPING_DIR="${OUTPUT_SWITCH}/Mapping_to_ref/"
	for f in $FILES
	do
		FOLDER_NAME=${f##*reads/}
		SAMPLE_NAME=${FOLDER_NAME%/*}
		FILE_1=${f}
		FILE_2=${f/_R1_val_1.fq/_R2_val_2.fq}
		if [ -f ${FILE_1} ]; then
			echo "Processing sample ${SAMPLE_NAME}"
		else
			echo "Read files cannot be opened for sample ${SAMPLE_NAME}, please check trimmed reads are generated in the folder ${OUTPUT_SWITCH}/Trimmed_reads/${SAMPLE_NAME}"
			echo "Reads can be trimmed usion option -1. If trimmed reads are present, Trimmed reads may contain a different prefix than ${R_PREFIX}" 
			echo "Please provide a correct prefix with -p";
			exit 1;
		fi
		mkdir -p ${MAPPING_DIR}${SAMPLE_NAME}
		cd ${MAPPING_DIR}${SAMPLE_NAME}
		echo "Mapping ${FILE_1}"
		echo "Mapping ${FILE_2}"
		bowtie2 -x ${G_PATH}_index -1 $FILE_1 -2 $FILE_2 -X 600 --fr -p ${CORES} --met-file ${SAMPLE_NAME}_metrix.txt --quiet | samtools view -bS - > ${SAMPLE_NAME}.bam
		wait
		samtools sort ${SAMPLE_NAME}.bam -l 9 -o ${SAMPLE_NAME}.sorted.bam
		wait
		samtools view -bq ${BAM_MAP_FILTER} ${SAMPLE_NAME}.sorted.bam > ${SAMPLE_NAME}.sorted.filtered.bam
		wait
		samtools index ${SAMPLE_NAME}.sorted.filtered.bam
		wait
		rm ${SAMPLE_NAME}.bam
		rm ${SAMPLE_NAME}.sorted.bam
		cd ${CURRENT_DIR}
		echo "Finished processing sample ${SAMPLE_NAME}"
	done
	echo "Finished mapping trimmed reads"
fi

#################################################
# Option 3, Generate coverage analysis plots
##################################################
# If this part of the sript does not work on your system, you can also try runnig the R script independently

if [ "$COV_ANALYSIS" = true ]; then
	echo "Starting coverage analysis [Option -3]"
	if [ "$R_PATH" = false ]; then
		echo "Option -r not supplied, cannot find read folder, exit";
		exit 1;
	fi
	
	command -v bedtools >/dev/null 2>&1 || { echo >&2 "Bedtools is not installed";
		if [ "$INSTALLER_SWITCH" = true ]; then
			echo "Installing now.";
			wget https://github.com/arq5x/bedtools2/releases/download/v2.29.1/bedtools-2.29.1.tar.gz -P ${INSTALL_DIR} -q -o /dev/null
			wait $!;
			tar -zxf ${INSTALL_DIR}/bedtools-2.29.1.tar.gz --directory ${INSTALL_DIR}/ 
			wait $!;
			rm ${INSTALL_DIR}/bedtools-2.29.1.tar.gz ;
			cd ${INSTALL_DIR}/bedtools2/
			make ;
			wait $!;
			export PATH=$PATH:${INSTALL_DIR}/bedtools2/bin/;
			cd ${CURRENT_DIR}
		else
			echo "Use option -i for automatic instalation, or add you local instalation to your PATH";
			exit 1;
		fi
	}	
	command -v R >/dev/null 2>&1 || { echo >&2 "R is not installed";
		echo "This software should be installed through sudo, therefore exiting";
		echo "More information on https://cran.r-project.org/bin/linux/ubuntu/README.html";
		exit 1;
	}
	MAPPING_DIR1="${OUTPUT_SWITCH}/Coverage_analysis"
	mkdir -p ${MAPPING_DIR1}
	echo -n "" > ${MAPPING_DIR1}/sample_reads.txt
	FILES="${CURRENT_DIR}/${OUTPUT_SWITCH}/Trimmed_reads/*/*_val_1.fq"
	for f in $FILES
	do
		FOLDER_NAME=${f##*Trimmed_reads/}
		SAMPLE_NAME=${FOLDER_NAME%/*}
		echo -n "${SAMPLE_NAME}" >> ${MAPPING_DIR1}/sample_reads.txt
		cat ${f} | echo -e "\t$((`wc -l`/2))" >> ${MAPPING_DIR1}/sample_reads.txt
	done
	
	MAPPING_DIR2="${OUTPUT_SWITCH}/Coverage_analysis/Coverages_per_sample"
	mkdir -p ${MAPPING_DIR2}
	FILES="${CURRENT_DIR}/${OUTPUT_SWITCH}/Mapping_to_ref/*/*.sorted.filtered.bam"
	for f in $FILES
	do
		FOLDER_NAME=${f##*Mapping_to_ref/}
		SAMPLE_NAME=${FOLDER_NAME%/*}
		echo "Calculated coverage for sample ${SAMPLE_NAME}"
		bedtools genomecov -bg -split -ibam ${f} > ${MAPPING_DIR2}/${SAMPLE_NAME}_coverage.tsv
	done
	R_LIBRARY_PATH="${INSTALL_DIR}/R_Lib"
	mkdir -p ${R_LIBRARY_PATH}
	R_SCRIPT_PATH="${SCRIPT_DIR}MEAP_coverage_analysis.R"
	Rscript --vanilla ${R_SCRIPT_PATH} ${R_LIBRARY_PATH} ${MAPPING_DIR1}/sample_reads.txt ${MAPPING_DIR2}/ ${MAPPING_DIR1}/ &> /dev/null
	echo "Coverage analysis finished. The resultant Coverage_distributions.pdf, Sample_read_quality.pdf and Analyzed_Coverage_Data.tsv output files can be found in ${MAPPING_DIR1}/"
fi

echo "Pipeline completed, data is ready for genotyping. All files are now available in ${POST_PROCESS_DIR}/"
exit 1